markdown: kramdown
highlighter: pygments
permalink: /:year/:month/:day/:title.html
name: "医生生病了"

kramdown:
  input: GFM

author: "sheng"
atom-baseurl: "http://websay.me"

navigations:
  - title: Archive
    class: fa fa-list-ul
    href: /archive.html
  - title: Tags
    class: fa fa-tags
    href: /tags.html
  - title: About
    class: fa fa-user
    href: /about.html